..........
----------------------------------------------------------------------
Ran 10 tests in 0.001s

OK
.
======================================================================
FAIL: test_cl (cpu.TestMath) (a=0, n=1, carry=0)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/PatrickDoyle/projects/cpu/cpu.py", line 600, in test_cl
    self.assertEqual( 1 * ( a >= n ), self.cpu.carry )
AssertionError: 0 != 1

----------------------------------------------------------------------
Ran 2 tests in 0.012s

FAILED (failures=1)
